# Generated by Django 6.1 on 2026-08-30 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computer_name', models.CharField(max_length=255, unique=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('login_account', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_addresses', models.CharField(blank=True, max_length=1024, null=True)),
                ('mac_addresses', models.CharField(blank=True, max_length=1024, null=True)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('os_build', models.CharField(blank=True, max_length=255, null=True)),
                ('system_installed_at', models.CharField(blank=True, max_length=255, null=True)),
                ('last_report_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField()),
                ('modified_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('import_status', models.CharField(max_length=20)),
                ('archived_path', models.TextField(blank=True)),
                ('parse_error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain_Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('login_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ou', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_workstations', models.TextField(blank=True, null=True)),
                ('last_login_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain_Computer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computer_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ou', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain_Controller_Config',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='主域控', max_length=100)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=389)),
                ('use_ssl', models.BooleanField(default=False)),
                ('base_dn', models.CharField(blank=True, help_text='例如：DC=example,DC=com', max_length=500)),
                ('bind_username', models.CharField(blank=True, max_length=255)),
                ('bind_password', models.CharField(blank=True, max_length=255)),
                ('user_filter', models.CharField(default='(&(objectCategory=person)(objectClass=user))', max_length=500)),
                ('computer_filter', models.CharField(default='(objectCategory=computer)', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.URLField(blank=True, max_length=500, null=True)),
                ('api_username', models.CharField(blank=True, max_length=255, null=True)),
                ('api_password', models.CharField(blank=True, max_length=255, null=True)),
                ('api_token', models.CharField(blank=True, max_length=500, null=True)),
                ('verify_ssl', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network_Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('leader', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('platform_user_id', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('server_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=20)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.URLField(blank=True, max_length=500, null=True)),
                ('api_token', models.CharField(blank=True, max_length=500, null=True)),
                ('verify_ssl', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='success', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_items', models.JSONField(blank=True, default=list)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='net.computer')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='net.computerlogfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Error_Computer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='net.computeranalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='success', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reachable', models.BooleanField(default=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='net.monitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Error_Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_message', models.JSONField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='net.monitor_inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Network_Device_Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='success', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reachable', models.BooleanField(default=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='net.network_device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Error_Network_Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_message', models.JSONField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='net.network_device_inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Server_Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='success', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reachable', models.BooleanField(default=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='net.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Error_Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_message', models.JSONField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='net.server_inspection')),
            ],
        ),
    ]
