# Generated by Django 6.1 on 2026-08-30 17:19

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import net.models.tasks
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerAnalysisProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('scan_directories', models.JSONField(blank=True, default=list, validators=[net.models.tasks.validate_string_list])),
                ('recursive', models.BooleanField(default=False)),
                ('processed_directory', models.TextField(blank=True)),
                ('failed_directory', models.TextField(blank=True)),
                ('file_time_mode', models.CharField(choices=[('recent_days', '最近 N 天'), ('date_range', '指定起止日期')], default='recent_days', max_length=20)),
                ('recent_days', models.PositiveSmallIntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('range_start_date', models.DateField(blank=True, null=True)),
                ('range_end_date', models.DateField(blank=True, null=True)),
                ('analysis_items', models.JSONField(blank=True, default=list, validators=[net.models.tasks.validate_string_list])),
                ('concurrent_workers', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)])),
                ('alert_policy_mode', models.CharField(choices=[('inherit', '继承默认告警策略'), ('override', '使用项目告警策略')], default='inherit', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('network_device', '网络设备'), ('server', '服务器'), ('monitor', '安防设备')], max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('selected_items', models.JSONField(blank=True, default=list, validators=[net.models.tasks.validate_string_list])),
                ('target_selector', models.JSONField(blank=True, default=dict, validators=[net.models.tasks.validate_json_object])),
                ('timeout_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)])),
                ('concurrent_workers', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)])),
                ('alert_policy_mode', models.CharField(choices=[('inherit', '继承默认告警策略'), ('override', '使用项目告警策略')], default='inherit', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device_type', 'name'), name='net_profile_device_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('interval', '间隔执行'), ('daily', '每天执行')], max_length=16)),
                ('interval_value', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('interval_unit', models.CharField(blank=True, choices=[('minutes', '分钟'), ('hours', '小时')], default='', max_length=16)),
                ('daily_time', models.TimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='net.computeranalysisprofile')),
                ('inspection_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='net.inspectionprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('inspection', '设备巡检'), ('computer_analysis', '计算机日志分析')], max_length=32)),
                ('source', models.CharField(choices=[('manual', '手动执行'), ('scheduled', '定时执行')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('queued', '等待'), ('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('cancelled', '已取消')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('profile_snapshot', models.JSONField(blank=True, default=dict, validators=[net.models.tasks.validate_json_object])),
                ('parameters_snapshot', models.JSONField(blank=True, default=dict, validators=[net.models.tasks.validate_json_object])),
                ('selected_items_snapshot', models.JSONField(blank=True, default=list, validators=[net.models.tasks.validate_string_list])),
                ('target_scope_snapshot', models.JSONField(blank=True, default=dict, validators=[net.models.tasks.validate_json_object])),
                ('scope_key', models.CharField(max_length=64)),
                ('active_scope_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('total_targets', models.PositiveIntegerField(default=0)),
                ('completed_targets', models.PositiveIntegerField(default=0)),
                ('successful_targets', models.PositiveIntegerField(default=0)),
                ('failed_targets', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='net.computeranalysisprofile')),
                ('inspection_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='net.inspectionprofile')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='net.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTargetRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('network_device', '网络设备'), ('server', '服务器'), ('monitor', '安防设备'), ('computer_log', '计算机日志')], max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('target_snapshot', models.JSONField(blank=True, default=dict, validators=[net.models.tasks.validate_json_object])),
                ('status', models.CharField(choices=[('queued', '等待'), ('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('cancelled', '已取消')], default='queued', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_type', models.CharField(blank=True, max_length=64)),
                ('result_id', models.CharField(blank=True, max_length=64)),
                ('result_snapshot', models.JSONField(blank=True, default=dict, validators=[net.models.tasks.validate_json_object])),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_runs', to='net.taskrun')),
            ],
        ),
        migrations.AddField(
            model_name='computeranalysis',
            name='task_target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_record', to='net.tasktargetrun'),
        ),
        migrations.AddField(
            model_name='monitor_inspection',
            name='task_target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_record', to='net.tasktargetrun'),
        ),
        migrations.AddField(
            model_name='network_device_inspection',
            name='task_target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_record', to='net.tasktargetrun'),
        ),
        migrations.AddField(
            model_name='server_inspection',
            name='task_target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_record', to='net.tasktargetrun'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', False)), models.Q(('analysis_profile__isnull', False), ('inspection_profile__isnull', True)), _connector='OR'), name='net_schedule_one_profile_ck'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('daily_time__isnull', True), ('interval_unit__in', ('minutes', 'hours')), ('interval_value__gt', 0), ('interval_value__isnull', False), ('kind', 'interval')), models.Q(('daily_time__isnull', False), ('interval_unit', ''), ('interval_value__isnull', True), ('kind', 'daily')), _connector='OR'), name='net_schedule_kind_fields_ck'),
        ),
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(fields=['status', 'available_at'], name='net_task_status_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(fields=['lease_expires_at'], name='net_task_lease_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(fields=['schedule', 'created_at'], name='net_task_sched_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_scope_key', models.F('scope_key')), ('active_scope_key__isnull', False), ('status__in', ('queued', 'running'))), models.Q(('active_scope_key__isnull', True), ('status__in', ('success', 'partial', 'failed', 'cancelled'))), _connector='OR'), name='net_task_active_scope_ck'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100), ('completed_targets__lte', models.F('total_targets')), ('successful_targets__lte', models.F('completed_targets')), ('failed_targets__lte', models.F('completed_targets')), ('completed_targets__gte', django.db.models.expressions.CombinedExpression(models.F('successful_targets'), '+', models.F('failed_targets')))), name='net_task_progress_counts_ck'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('lease_expires_at__isnull', True), ('status', 'queued')), models.Q(('finished_at__isnull', True), ('lease_expires_at__isnull', False), ('started_at__isnull', False), ('status', 'running'), models.Q(('worker_id', ''), _negated=True)), models.Q(('completed_targets', models.F('total_targets')), ('failed_targets', 0), ('finished_at__isnull', False), ('lease_expires_at__isnull', True), ('progress', 100), ('status', 'success'), ('successful_targets', models.F('total_targets'))), models.Q(('completed_targets', models.F('total_targets')), ('failed_targets__gt', 0), ('finished_at__isnull', False), ('lease_expires_at__isnull', True), ('progress', 100), ('status', 'partial'), ('successful_targets__gt', 0), ('completed_targets', django.db.models.expressions.CombinedExpression(models.F('successful_targets'), '+', models.F('failed_targets')))), models.Q(('completed_targets', models.F('total_targets')), ('failed_targets', models.F('total_targets')), ('finished_at__isnull', False), ('lease_expires_at__isnull', True), ('progress', 100), ('status', 'failed'), ('successful_targets', 0)), models.Q(('finished_at__isnull', False), ('lease_expires_at__isnull', True), ('status', 'cancelled')), _connector='OR'), name='net_task_state_shape_ck'),
        ),
        migrations.AddIndex(
            model_name='tasktargetrun',
            index=models.Index(fields=['task', 'status'], name='net_target_task_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktargetrun',
            constraint=models.UniqueConstraint(fields=('task', 'target_type', 'target_id'), name='net_task_target_uniq'),
        ),
    ]
