# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0002_task_profiles_and_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlogfile',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
