# Generated by Django 6.1 on 2026-08-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0005_computer_scan_tasks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('inspection_profile',), name='net_schedule_inspection_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('analysis_profile',), name='net_schedule_analysis_uniq'),
        ),
    ]
