# Generated by Django 6.1 on 2026-08-31 00:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import net.models.alerts
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0006_schedule_net_schedule_inspection_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('channel_type', models.CharField(choices=[('feishu', '飞书'), ('dingtalk', '钉钉'), ('email', '邮件')], max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict, validators=[net.models.alerts.validate_finite_json])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('default_slot', models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True)),
                ('mode', models.CharField(choices=[('inherit', '继承默认告警策略'), ('override', '使用项目告警策略')], default='inherit', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_policies', to='net.computeranalysisprofile')),
                ('channels', models.ManyToManyField(blank=True, related_name='policies', to='net.alertchannel')),
                ('inspection_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_policies', to='net.inspectionprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(max_length=32)),
                ('profile_id', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('abnormal', '异常告警'), ('recovery', '恢复通知')], max_length=16)),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('delivered', '已送达'), ('partial', '部分送达'), ('failed', '发送失败')], default='pending', max_length=16)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('findings', models.JSONField(default=list, validators=[net.models.alerts.validate_finite_json])),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='net.tasktargetrun')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='net.taskrun')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='net.alertpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(max_length=32)),
                ('profile_id', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('finding_key', models.CharField(max_length=191)),
                ('status', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=16)),
                ('finding_snapshot', models.JSONField(blank=True, default=dict, validators=[net.models.alerts.validate_finite_json])),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_abnormal_at', models.DateTimeField(blank=True, null=True)),
                ('last_normal_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_for_states', to='net.alertevent')),
            ],
        ),
        migrations.AddField(
            model_name='alertevent',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='events', to='net.alertstate'),
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('sent', '发送成功'), ('retry', '等待重试'), ('failed', '发送失败')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('response_summary', models.CharField(blank=True, max_length=1000)),
                ('error_summary', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='net.alertchannel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='net.alertevent')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='net_alert_delivery_retry_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'channel'), name='net_alert_delivery_event_channel_uniq'), models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1), ('max_attempts__lte', 5), ('attempt_count__lte', models.F('max_attempts'))), name='net_alert_delivery_attempt_limit_ck'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'sending', 'sent', 'retry', 'failed'))), name='net_alert_delivery_status_ck')],
            },
        ),
        migrations.AddConstraint(
            model_name='alertpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('default_slot', 'default'), ('inspection_profile__isnull', True), ('is_default', True), ('mode', 'override')), models.Q(('analysis_profile__isnull', True), ('default_slot__isnull', True), ('inspection_profile__isnull', False), ('is_default', False)), models.Q(('analysis_profile__isnull', False), ('default_slot__isnull', True), ('inspection_profile__isnull', True), ('is_default', False)), _connector='OR'), name='net_alert_policy_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='alertpolicy',
            constraint=models.UniqueConstraint(fields=('inspection_profile',), name='net_alert_policy_inspection_uniq'),
        ),
        migrations.AddConstraint(
            model_name='alertpolicy',
            constraint=models.UniqueConstraint(fields=('analysis_profile',), name='net_alert_policy_analysis_uniq'),
        ),
        migrations.AddIndex(
            model_name='alertstate',
            index=models.Index(fields=['profile_type', 'profile_id', 'target_type', 'target_id'], name='net_alert_state_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertstate',
            constraint=models.UniqueConstraint(fields=('profile_type', 'profile_id', 'target_type', 'target_id', 'finding_key'), name='net_alert_state_finding_uniq'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['status', 'occurred_at'], name='net_alert_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['profile_type', 'profile_id'], name='net_alert_event_profile_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertevent',
            constraint=models.UniqueConstraint(fields=('target_run', 'event_type'), name='net_alert_event_target_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='alertchannel',
            constraint=models.CheckConstraint(condition=models.Q(channel_type__in=('feishu', 'dingtalk', 'email')), name='net_alert_channel_type_ck'),
        ),
        migrations.AddConstraint(
            model_name='alertpolicy',
            constraint=models.CheckConstraint(condition=models.Q(mode__in=('inherit', 'override')), name='net_alert_policy_mode_ck'),
        ),
        migrations.AddConstraint(
            model_name='alertstate',
            constraint=models.CheckConstraint(condition=models.Q(status__in=('normal', 'abnormal')), name='net_alert_state_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='alertevent',
            constraint=models.CheckConstraint(condition=models.Q(event_type__in=('abnormal', 'recovery')), name='net_alert_event_type_ck'),
        ),
        migrations.AddConstraint(
            model_name='alertevent',
            constraint=models.CheckConstraint(condition=models.Q(status__in=('pending', 'sending', 'delivered', 'partial', 'failed')), name='net_alert_event_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='alertdelivery',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(status='sent', delivered_at__isnull=False, next_attempt_at__isnull=True)
                    | models.Q(status='retry', delivered_at__isnull=True, next_attempt_at__isnull=False,
                               attempt_count__lt=models.F('max_attempts'))
                    | models.Q(status__in=('pending', 'sending', 'failed'),
                               delivered_at__isnull=True, next_attempt_at__isnull=True)
                ),
                name='net_alert_delivery_time_ck',
            ),
        ),
    ]
