# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0007_alerting'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdelivery',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='lease_token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RemoveConstraint(
            model_name='alertdelivery',
            name='net_alert_delivery_time_ck',
        ),
        migrations.AddConstraint(
            model_name='alertdelivery',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(status='sent', delivered_at__isnull=False, next_attempt_at__isnull=True)
                    | models.Q(status='retry', delivered_at__isnull=True, next_attempt_at__isnull=False,
                               attempt_count__lt=models.F('max_attempts'))
                    | models.Q(status='sending', delivered_at__isnull=True,
                               next_attempt_at__isnull=True, lease_expires_at__isnull=False,
                               lease_token__gt='')
                    | models.Q(status__in=('pending', 'failed'), delivered_at__isnull=True,
                               next_attempt_at__isnull=True, lease_expires_at__isnull=True,
                               lease_token='')
                ),
                name='net_alert_delivery_time_ck',
            ),
        ),
    ]
