# Generated by Django 6.1 on 2026-08-31 04:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0010_alert_test_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleSyncSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('feishu', '飞书'), ('dingtalk', '钉钉')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('source_key', models.CharField(max_length=191, unique=True)),
                ('credentials', models.JSONField(default=dict, editable=False, serialize=False)),
                ('root_department_ids', models.JSONField(blank=True, default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('source_type__in', ('feishu', 'dingtalk'))), name='net_people_sync_source_type_ck')],
            },
        ),
        migrations.AddField(
            model_name='people',
            name='sync_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='net.peoplesyncsource'),
        ),
    ]
