# Generated by Django 6.1 on 2026-08-31 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0011_people_sync_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='people_applied_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='people_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='net.peoplesyncsource'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('inspection', '设备巡检'), ('computer_analysis', '计算机日志分析'), ('computer_scan', '计算机日志扫描'), ('people_test', '人员目录连接测试'), ('people_preview', '人员目录同步预览')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktargetrun',
            name='target_type',
            field=models.CharField(choices=[('network_device', '网络设备'), ('server', '服务器'), ('monitor', '安防设备'), ('computer_log', '计算机日志'), ('computer_scan', '计算机日志扫描'), ('people_source', '人员目录来源')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', False), ('schedule__isnull', True), ('source', 'manual'), ('task_type__in', ('people_test', 'people_preview'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', False), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'inspection')), models.Q(('analysis_profile__isnull', False), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type__in', ('computer_analysis', 'computer_scan'))), _connector='OR'), name='net_task_binding_shape_ck'),
        ),
    ]
