# Generated by Django 6.1 on 2026-08-31 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0012_people_directory_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlogfile',
            name='upload_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_log', to='net.taskrun'),
        ),
        migrations.AddField(
            model_name='tasktargetrun',
            name='scan_logs',
            field=models.ManyToManyField(blank=True, related_name='intended_scans', to='net.computerlogfile'),
        ),
    ]
