# Generated by Django 6.1 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0014_asset_inventory_and_people_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='cpu_core_count',
            new_name='cpu_physical_core_count',
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu_logical_processor_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='disk_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
