# Generated by Django 6.1 on 2026-09-01 08:13

import django.db.models.deletion
import net.models.domain
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0015_pc_inventory_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create_user', '添加用户'), ('move_ou', '移动到 OU'), ('add_group', '加入安全组'), ('remove_group', '移出安全组'), ('reset_password', '重置密码'), ('must_change_password', '下次登录修改密码'), ('password_never_expires', '密码永不过期'), ('unlock', '解锁'), ('enable', '启用'), ('disable', '停用')], max_length=32)),
                ('object_type', models.CharField(choices=[('account', '域账号'), ('computer', '域计算机')], max_length=16)),
                ('status', models.CharField(choices=[('queued', '等待'), ('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('cancelled', '已取消')], default='queued', max_length=16)),
                ('target_count', models.PositiveIntegerField()),
                ('parameter_summary', models.JSONField(blank=True, default=dict, validators=[net.models.domain.validate_parameter_summary])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('manage_domain_operations', 'Can manage domain operations')],
            },
        ),
        migrations.CreateModel(
            name='DomainOperationSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_payload', models.BinaryField()),
                ('purpose_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='taskrun',
            name='net_task_binding_shape_ck',
        ),
        migrations.AddField(
            model_name='domain_account',
            name='distinguished_name',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='domain_account',
            name='object_guid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='domain_computer',
            name='distinguished_name',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='domain_computer',
            name='object_guid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('inspection', '设备巡检'), ('computer_analysis', '计算机日志分析'), ('computer_scan', '计算机日志扫描'), ('people_test', '人员目录连接测试'), ('people_preview', '人员目录同步预览'), ('domain_operation', '域控操作')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktargetrun',
            name='target_type',
            field=models.CharField(choices=[('network_device', '网络设备'), ('server', '服务器'), ('monitor', '安防设备'), ('computer_log', '计算机日志'), ('computer_scan', '计算机日志扫描'), ('people_source', '人员目录来源'), ('domain_account', '域账号'), ('domain_computer', '域计算机')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', False), ('schedule__isnull', True), ('source', 'manual'), ('task_type__in', ('people_test', 'people_preview'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', False), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'inspection')), models.Q(('analysis_profile__isnull', False), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type__in', ('computer_analysis', 'computer_scan'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('schedule__isnull', True), ('source', 'manual'), ('task_type', 'domain_operation')), _connector='OR'), name='net_task_binding_shape_ck'),
        ),
        migrations.AddField(
            model_name='domainoperation',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainoperation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_operation', to='net.taskrun'),
        ),
        migrations.AddField(
            model_name='domainoperationsecret',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret', to='net.domainoperation'),
        ),
    ]
