# Generated by Django 6.1 on 2026-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0016_domain_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktargetrun',
            name='execution_scope_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='tasktargetrun',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('execution_scope_key__isnull', False),
                    ('status__in', frozenset(['queued', 'running'])),
                ),
                fields=('execution_scope_key',),
                name='net_target_active_execution_scope_uniq',
            ),
        ),
    ]
