# Generated by Django 6.1 on 2026-09-02 09:01

import django.core.validators
import net.models.tasks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0017_domain_target_execution_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='cpu_max_percent',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='defender_scan_max_days',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='defender_update_max_days',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='kms_servers',
            field=models.JSONField(blank=True, default=list, validators=[net.models.tasks.validate_string_list]),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='memory_max_percent',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='minimum_windows_release',
            field=models.CharField(blank=True, default='23H2', max_length=16),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='patch_max_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='software_policy_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='uptime_max_hours',
            field=models.PositiveIntegerField(default=168, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(87600)]),
        ),
    ]
