# Generated by Django 6.1 on 2026-09-03 01:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0018_computer_analysis_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainoperation',
            name='action',
            field=models.CharField(choices=[('create_user', '添加用户'), ('move_ou', '移动到 OU'), ('add_group', '加入安全组'), ('reset_password', '重置密码'), ('must_change_password', '下次登录修改密码'), ('password_never_expires', '密码永不过期'), ('unlock', '解锁'), ('enable', '启用'), ('disable', '停用')], max_length=32),
        ),
        migrations.AddField(
            model_name='domain_controller_config',
            name='group_filter',
            field=models.CharField(default='(objectCategory=group)', max_length=500),
        ),
        migrations.CreateModel(
            name='Domain_Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_guid', models.UUIDField(blank=True, null=True, unique=True)),
                ('distinguished_name', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('login_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ou', models.CharField(blank=True, max_length=255)),
                ('group_scope', models.CharField(choices=[('domain_local', '域本地'), ('global', '全局'), ('universal', '通用'), ('unknown', '未知')], default='unknown', max_length=16)),
                ('group_category', models.CharField(choices=[('security', '安全组'), ('distribution', '通讯组')], default='security', max_length=16)),
                ('member_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
