# Generated by Django 6.1.1 on 2026-09-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0020_security_device_and_server_inventory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='net_schedule_one_profile_ck',
        ),
        migrations.RemoveConstraint(
            model_name='taskrun',
            name='net_task_binding_shape_ck',
        ),
        migrations.AddField(
            model_name='schedule',
            name='people_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='net.peoplesyncsource'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('inspection', '设备巡检'), ('computer_analysis', '计算机日志分析'), ('computer_scan', '计算机日志扫描'), ('people_test', '人员目录连接测试'), ('people_preview', '人员目录同步预览'), ('people_sync', '人员自动同步'), ('domain_operation', '域控操作')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', False), ('people_source__isnull', True)), models.Q(('analysis_profile__isnull', False), ('inspection_profile__isnull', True), ('people_source__isnull', True)), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', False)), _connector='OR'), name='net_schedule_one_profile_ck'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('people_source',), name='net_schedule_people_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', False), ('schedule__isnull', True), ('source', 'manual'), ('task_type__in', ('people_test', 'people_preview'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', False), ('schedule__isnull', False), ('source', 'scheduled'), ('task_type', 'people_sync')), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', False), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'inspection')), models.Q(('analysis_profile__isnull', False), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type__in', ('computer_analysis', 'computer_scan'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('schedule__isnull', True), ('source', 'manual'), ('task_type', 'domain_operation')), _connector='OR'), name='net_task_binding_shape_ck'),
        ),
    ]
