# Generated by Django 6.1.1 on 2026-09-04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0021_people_sync_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='network_device',
            name='snmp_auth_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_auth_protocol',
            field=models.CharField(blank=True, choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha224', 'SHA-224'), ('sha256', 'SHA-256'), ('sha384', 'SHA-384'), ('sha512', 'SHA-512')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_community',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_context_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_port',
            field=models.PositiveIntegerField(default=161, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_priv_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_priv_protocol',
            field=models.CharField(blank=True, choices=[('des', 'DES'), ('aes128', 'AES-128'), ('aes192', 'AES-192'), ('aes256', 'AES-256')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_retries',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_security_level',
            field=models.CharField(choices=[('noAuthNoPriv', 'noAuthNoPriv'), ('authNoPriv', 'authNoPriv'), ('authPriv', 'authPriv')], default='noAuthNoPriv', max_length=12),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='network_device',
            name='snmp_version',
            field=models.CharField(choices=[('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='network_device',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('ssh', 'SSH'), ('snmp', 'SNMP'), ('hybrid', 'SSH + SNMP'), ('auto', '自动')], default='ssh', max_length=255, null=True),
        ),
    ]
