# Generated by Django 6.1.1 on 2026-09-07 02:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0023_taskrun_partial_target_aggregation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerLogTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_source_path', models.TextField()),
                ('remote_archive_path', models.TextField(blank=True)),
                ('local_staging_path', models.TextField(blank=True)),
                ('remote_size', models.PositiveBigIntegerField(default=0)),
                ('observed_mtime', models.DateTimeField()),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('stage', models.CharField(choices=[('discovered', '已发现'), ('downloaded', '已下载'), ('imported', '已导入'), ('archive_pending', '等待归档'), ('completed', '已完成'), ('failed', '失败')], default='discovered', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCLogSourceConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('smb', 'SMB'), ('ftp', 'FTP/FTPS')], max_length=8)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('share_name', models.CharField(blank=True, max_length=255)),
                ('remote_root_directory', models.TextField(blank=True)),
                ('remote_incoming_directory', models.TextField()),
                ('remote_processed_directory', models.TextField(default='processed')),
                ('remote_failed_directory', models.TextField(default='failed')),
                ('local_staging_directory', models.TextField()),
                ('terminal_windows_path', models.TextField()),
                ('terminal_macos_path', models.TextField(blank=True)),
                ('recursive', models.BooleanField(default=False)),
                ('file_time_mode', models.CharField(choices=[('recent_days', '最近 N 天'), ('date_range', '指定起止日期')], max_length=20)),
                ('recent_days', models.PositiveSmallIntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('range_start_date', models.DateField(blank=True, null=True)),
                ('range_end_date', models.DateField(blank=True, null=True)),
                ('ftp_passive', models.BooleanField(default=True)),
                ('ftp_use_tls', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCLogSourceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_payload', models.BinaryField()),
                ('purpose_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='upload_task',
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='collected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_files', to='net.computer'),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='platform',
            field=models.CharField(blank=True, choices=[('windows', 'Windows'), ('macos', 'macOS')], max_length=20),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='remote_source_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='source_protocol',
            field=models.CharField(blank=True, choices=[('smb', 'SMB'), ('ftp', 'FTP'), ('ftps', 'FTPS')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='computerlogfile',
            constraint=models.UniqueConstraint(condition=models.Q(('collected_date__isnull', False), ('computer__isnull', False), ('import_status', 'imported')), fields=('computer', 'collected_date'), name='net_pc_imported_log_daily_uniq'),
        ),
        migrations.AddField(
            model_name='computerlogtransfer',
            name='log_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='net.computerlogfile'),
        ),
        migrations.AddField(
            model_name='computerlogtransfer',
            name='task_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_transfers', to='net.tasktargetrun'),
        ),
        migrations.AddConstraint(
            model_name='pclogsourceconfig',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='net_pc_log_source_singleton_ck'),
        ),
        migrations.AddField(
            model_name='computerlogtransfer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='net.pclogsourceconfig'),
        ),
        migrations.AddField(
            model_name='pclogsourcecredential',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='net.pclogsourceconfig'),
        ),
        migrations.AddIndex(
            model_name='computerlogtransfer',
            index=models.Index(fields=['source', 'stage'], name='net_pc_xfer_source_stage_idx'),
        ),
        migrations.AddConstraint(
            model_name='computerlogtransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('stage__in', ('discovered', 'downloaded', 'imported', 'archive_pending'))), fields=('source', 'remote_source_path', 'observed_mtime'), name='net_pc_transfer_active_identity_uniq'),
        ),
    ]
