# Generated by Django 6.1.1 on 2026-09-07 02:28

from django.db import migrations, models


def retire_unidentified_development_logs(apps, schema_editor):
    # Old development evidence has no daily identity. Keep it readable, but do
    # not claim it is a formally imported daily log under the new contract.
    apps.get_model('net', 'ComputerLogFile').objects.filter(
        models.Q(computer__isnull=True) | models.Q(collected_date__isnull=True),
        import_status='imported',
    ).update(import_status='legacy')


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0024_pc_remote_log_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='computerlogfile',
            name='net_pc_imported_log_daily_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='computerlogtransfer',
            name='net_pc_transfer_active_identity_uniq',
        ),
        migrations.AlterField(
            model_name='computerlogtransfer',
            name='remote_source_path',
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='daily_import_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(import_status='imported', then=models.Value(1)), default=models.Value(None)), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='computerlogtransfer',
            name='active_identity_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(stage__in=('discovered', 'downloaded', 'imported', 'archive_pending'), then=models.Value(1)), default=models.Value(None)), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.RunPython(retire_unidentified_development_logs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='computerlogfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('import_status', 'imported'), _negated=True), models.Q(('computer__isnull', False), ('collected_date__isnull', False)), _connector='OR'), name='net_pc_import_identity_ck'),
        ),
        migrations.AddConstraint(
            model_name='computerlogfile',
            constraint=models.UniqueConstraint(fields=('computer', 'collected_date', 'daily_import_marker'), name='net_pc_imported_log_daily_uniq'),
        ),
        migrations.AddConstraint(
            model_name='computerlogtransfer',
            constraint=models.UniqueConstraint(fields=('source', 'remote_source_path', 'observed_mtime', 'active_identity_marker'), name='net_pc_transfer_active_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pclogsourceconfig',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ('smb', 'ftp'))), name='net_pc_log_source_type_ck'),
        ),
    ]
