# Generated by Django 6.1.1 on 2026-09-07 03:36

from django.db import migrations, models


def rename_development_task_types(apps, schema_editor):
    apps.get_model('net', 'TaskRun').objects.filter(task_type='computer_scan').update(task_type='computer_fetch')
    apps.get_model('net', 'TaskTargetRun').objects.filter(target_type='computer_scan').update(target_type='computer_source')


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0025_pc_remote_log_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskrun',
            name='net_task_binding_shape_ck',
        ),
        migrations.RenameField(
            model_name='tasktargetrun',
            old_name='scan_logs',
            new_name='fetched_logs',
        ),
        migrations.RunPython(rename_development_task_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('inspection', '设备巡检'), ('computer_analysis', '计算机日志分析'), ('computer_fetch', 'PC 日志获取'), ('people_test', '人员目录连接测试'), ('people_preview', '人员目录同步预览'), ('people_sync', '人员自动同步'), ('domain_operation', '域控操作')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktargetrun',
            name='target_type',
            field=models.CharField(choices=[('network_device', '网络设备'), ('server', '服务器'), ('monitor', '安防设备'), ('computer_log', '计算机日志'), ('computer_source', 'PC 日志来源'), ('people_source', '人员目录来源'), ('domain_account', '域账号'), ('domain_computer', '域计算机')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', False), ('schedule__isnull', True), ('source', 'manual'), ('task_type__in', ('people_test', 'people_preview'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', False), ('schedule__isnull', False), ('source', 'scheduled'), ('task_type', 'people_sync')), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', False), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'inspection')), models.Q(('analysis_profile__isnull', False), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type__in', ('computer_analysis', 'computer_fetch'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('schedule__isnull', True), ('source', 'manual'), ('task_type', 'domain_operation')), _connector='OR'), name='net_task_binding_shape_ck'),
        ),
    ]
