# Generated by Django 6.1.1 on 2026-09-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0026_pc_log_fetch_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computeranalysisprofile',
            name='failed_directory',
        ),
        migrations.RemoveField(
            model_name='computeranalysisprofile',
            name='file_time_mode',
        ),
        migrations.RemoveField(
            model_name='computeranalysisprofile',
            name='processed_directory',
        ),
        migrations.RemoveField(
            model_name='computeranalysisprofile',
            name='range_end_date',
        ),
        migrations.RemoveField(
            model_name='computeranalysisprofile',
            name='range_start_date',
        ),
        migrations.RemoveField(
            model_name='computeranalysisprofile',
            name='recent_days',
        ),
        migrations.RemoveField(
            model_name='computeranalysisprofile',
            name='recursive',
        ),
        migrations.RemoveField(
            model_name='computeranalysisprofile',
            name='scan_directories',
        ),
    ]
