# Generated by Django 6.1.1 on 2026-09-07 03:45

import django.core.validators
import net.models.tasks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0027_remove_local_scan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='cpu_temperature_max_celsius',
            field=models.PositiveSmallIntegerField(default=85, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='site_ip_prefixes',
            field=models.JSONField(blank=True, default=dict, validators=[net.models.tasks.validate_json_object]),
        ),
        migrations.AddField(
            model_name='computerlogtransfer',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
