# Generated by Django 6.1.1 on 2026-09-07 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0028_pc_source_snapshots_analysis_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktargetrun',
            name='analysis_handoff_task',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recovered_fetch_targets', to='net.taskrun'),
        ),
    ]
