# Generated by Django 6.1.1 on 2026-09-07 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0030_pc_source_windows_identity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='net_schedule_one_profile_ck',
        ),
        migrations.RemoveConstraint(
            model_name='taskrun',
            name='net_task_binding_shape_ck',
        ),
        migrations.AddField(
            model_name='schedule',
            name='domain_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='net.domain_controller_config'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('domain_sync', '域控同步'), ('inspection', '设备巡检'), ('computer_analysis', '计算机日志分析'), ('computer_fetch', 'PC 日志获取'), ('people_test', '人员目录连接测试'), ('people_preview', '人员目录同步预览'), ('people_sync', '人员自动同步'), ('domain_operation', '域控操作')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktargetrun',
            name='target_type',
            field=models.CharField(choices=[('domain_config', '域控目录'), ('network_device', '网络设备'), ('server', '服务器'), ('monitor', '安防设备'), ('computer_log', '计算机日志'), ('computer_source', 'PC 日志来源'), ('people_source', '人员目录来源'), ('domain_account', '域账号'), ('domain_computer', '域计算机')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('domain_config__isnull', True), ('inspection_profile__isnull', False), ('people_source__isnull', True)), models.Q(('analysis_profile__isnull', False), ('domain_config__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', True)), models.Q(('analysis_profile__isnull', True), ('domain_config__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', False)), models.Q(('analysis_profile__isnull', True), ('domain_config__isnull', False), ('inspection_profile__isnull', True), ('people_source__isnull', True)), _connector='OR'), name='net_schedule_one_profile_ck'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('domain_config',), name='net_schedule_domain_config_uniq'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', False), ('schedule__isnull', True), ('source', 'manual'), ('task_type__in', ('people_test', 'people_preview'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', False), ('schedule__isnull', False), ('source', 'scheduled'), ('task_type', 'people_sync')), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', False), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'inspection')), models.Q(('analysis_profile__isnull', False), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type__in', ('computer_analysis', 'computer_fetch'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'domain_sync')), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('schedule__isnull', True), ('source', 'manual'), ('task_type', 'domain_operation')), _connector='OR'), name='net_task_binding_shape_ck'),
        ),
    ]
