# Generated by Django 6.1.1 on 2026-09-09 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0042_task_alert_summaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network_device',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('ssh', 'SSH'), ('snmp', 'SNMP'), ('hybrid', 'SSH + SNMP'), ('auto', '自动')], default='auto', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DeviceCollectionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('networks', '网络设备'), ('servers', '服务器'), ('monitors', '安防设备')], max_length=16)),
                ('vendor', models.CharField(blank=True, default='', max_length=64)),
                ('subtype', models.CharField(blank=True, default='', max_length=32)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'vendor', 'subtype'), name='net_collection_template_scope')],
            },
        ),
        migrations.CreateModel(
            name='DeviceCollectionBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('networks', '网络设备'), ('servers', '服务器'), ('monitors', '安防设备')], max_length=16)),
                ('target_id', models.UUIDField()),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('encrypted_credentials', models.TextField(blank=True, default='', editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='net.devicecollectiontemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'target_id'), name='net_collection_binding_target')],
            },
        ),
    ]
