# Generated by Django 6.1.1 on 2026-09-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0044_access_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecollectiontemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='net.devicecollectiontemplate'),
        ),
    ]
