# Generated by Django 6.1.1 on 2026-09-10 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0045_collection_template_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='disk_max_percent',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
