# Generated by Django 6.1.1 on 2026-09-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0048_network_device_api_shared_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecollectiontemplate',
            name='version_match',
            field=models.CharField(blank=True, db_default='', default='', max_length=96, verbose_name='版本匹配关键字'),
        ),
        migrations.AddField(
            model_name='network_device',
            name='os_version',
            field=models.CharField(blank=True, db_default='', default='', max_length=1024, verbose_name='系统版本（自动采集）'),
        ),
        migrations.AddConstraint(
            model_name='devicecollectiontemplate',
            constraint=models.UniqueConstraint(fields=('kind', 'vendor', 'subtype', 'version_match'), name='net_collection_template_scope_v2'),
        ),
        migrations.RemoveConstraint(
            model_name='devicecollectiontemplate',
            name='net_collection_template_scope',
        ),
    ]
