# Generated by Django 6.1.1 on 2026-09-15 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0050_pc_software_policy_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainOU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_guid', models.UUIDField(blank=True, null=True, unique=True)),
                ('distinguished_name', models.CharField(db_index=True, max_length=1024)),
                ('name', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='domain_account',
            name='group_names',
            field=models.TextField(blank=True, db_default='', default='', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='domain_computer',
            name='group_names',
            field=models.TextField(blank=True, db_default='', default='', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='domain_group',
            name='is_available',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='domainoperation',
            name='action',
            field=models.CharField(choices=[('create_user', '添加用户'), ('move_ou', '移动到 OU'), ('add_group', '加入安全组'), ('remove_group', '移出分组'), ('reset_password', '重置密码'), ('must_change_password', '下次登录修改密码'), ('password_never_expires', '密码永不过期'), ('unlock', '解锁'), ('enable', '启用'), ('disable', '停用')], max_length=32),
        ),
        migrations.CreateModel(
            name='DomainMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='net.domain_account')),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='net.domain_computer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='net.domain_group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'account'), name='domain_group_account_unique'), models.UniqueConstraint(fields=('group', 'computer'), name='domain_group_computer_unique'), models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('computer__isnull', True)), models.Q(('account__isnull', True), ('computer__isnull', False)), _connector='OR'), name='domain_membership_one_target')],
            },
        ),
    ]
