# Generated by Django 6.1.1 on 2026-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0051_domain_memberships_and_ous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainoperation',
            name='action',
            field=models.CharField(choices=[('create_user', '添加用户'), ('move_ou', '移动到 OU'), ('add_group', '加入安全组'), ('remove_group', '移出分组'), ('move_group', '移动分组成员'), ('reset_password', '重置密码'), ('must_change_password', '下次登录修改密码'), ('password_never_expires', '密码永不过期'), ('unlock', '解锁'), ('enable', '启用'), ('disable', '停用')], max_length=32),
        ),
    ]
