# Generated by Django 6.1.1 on 2026-09-16 07:40

import django.db.models.deletion
from django.db import migrations, models



SECTIONS = {'系统信息概览': 'system_info', '网络信息': 'network_info', '计算机硬件资源情况': 'hardware_info', '日志文件元数据': 'log_metadata', 'Windows激活信息': 'windows_activation', 'KMS服务器连通情况': 'kms_connectivity', '当前与域服务器通讯情况': 'domain_communication', '已安装软件列表': 'installed_software', '当前运行进程清单': 'running_processes', 'BitLocker状态': 'bitlocker', 'WindowsDefender状态': 'defender', '系统更新历史': 'system_updates', '已应用策略': 'applied_policies', '浏览器插件情况': 'browser_extensions', '计算机和用户匹配情况': 'identity_match', '事件发现': 'event_findings', '采集诊断': 'collection_diagnostics'}

def backfill_top_level_columns(apps, schema_editor):
    from django.utils import timezone
    from django.utils.dateparse import parse_datetime
    Log = apps.get_model('net', 'ComputerLogFile')
    alias = schema_editor.connection.alias
    # The original JSON column remains untouched for lossless historical evidence.
    last_pk = 0
    while True:
        batch = list(Log.objects.using(alias).filter(pk__gt=last_pk).order_by('pk')[:100])
        if not batch:
            break
        for row in batch:
            value = row.legacy_payload if isinstance(row.legacy_payload, dict) else {}
            raw_time = value.get('日志时间')
            try:
                stamp = parse_datetime(raw_time) if isinstance(raw_time, str) else None
            except ValueError:
                stamp = None
            stamp = stamp or row.modified_at
            if stamp and timezone.is_naive(stamp):
                stamp = timezone.make_aware(stamp)
            row.collected_at = stamp
            row.present_sections = [key for key in SECTIONS if key in value]
            row.extra_fields = {key: item for key, item in value.items()
                                if key not in SECTIONS and key not in ('platform', '日志时间')}
            for key, field in SECTIONS.items():
                setattr(row, field, value.get(key))
        Log.objects.using(alias).bulk_update(batch,
            ['collected_at', 'present_sections', 'extra_fields', *SECTIONS.values()], batch_size=100)
        last_pk = batch[-1].pk


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0052_domain_operation_move_group'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField('computerlogfile', 'payload', 'legacy_payload'),
                migrations.AlterField('computerlogfile', 'legacy_payload',
                    models.JSONField(null=True, blank=True, editable=False, db_column='payload')),
            ],
        ),
        migrations.CreateModel(
            name='PCUploadConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('endpoint_url', models.URLField(max_length=1000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('log_retention', models.CharField(choices=[('daily_latest', '每天仅保留最新版本（往日保留）'), ('all', '保留全部版本')], default='daily_latest', max_length=20)),
                ('encrypted_token', models.BinaryField(blank=True, default=bytes)),
                ('token_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='computerlogfile',
            name='net_pc_imported_log_daily_uniq',
        ),
        migrations.AddField(
            model_name='computeranalysis',
            name='analysis_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='computeranalysis',
            name='analysis_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='net.computeranalysisprofile'),
        ),
        migrations.AddField(
            model_name='computeranalysis',
            name='retention_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computeranalysis',
            name='source_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computeranalysisprofile',
            name='analysis_retention',
            field=models.CharField(choices=[('daily_latest', '每天仅保留最新版本（往日保留）'), ('all', '保留全部版本')], default='daily_latest', max_length=20),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='applied_policies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='bitlocker',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='browser_extensions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='collected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='collection_diagnostics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='defender',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='domain_communication',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='event_findings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='hardware_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='identity_match',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='installed_software',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='kms_connectivity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='log_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='network_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='present_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='retained',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='running_processes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='system_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='system_updates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlogfile',
            name='windows_activation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computeranalysis',
            name='log_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='net.computerlogfile'),
        ),
        migrations.AlterField(
            model_name='computerlogfile',
            name='source_protocol',
            field=models.CharField(blank=True, choices=[('api', 'API 上报'), ('smb', 'SMB'), ('ftp', 'FTP'), ('ftps', 'FTPS')], max_length=8),
        ),
        migrations.AddIndex(
            model_name='computerlogfile',
            index=models.Index(fields=['computer', 'collected_at', 'id'], name='net_pc_latest_log_idx'),
        ),
        migrations.AddConstraint(
            model_name='pcuploadconfig',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='net_pc_upload_singleton_ck'),
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='daily_import_marker',
        ),

        migrations.RunPython(backfill_top_level_columns, migrations.RunPython.noop),
    ]
