# Generated by Django 6.1.1 on 2026-09-18 12:05

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def delete_retired_pc_source_data(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model('net', 'ComputerLogArchive').objects.using(alias).all().delete()
    apps.get_model('net', 'ComputerLogTransfer').objects.using(alias).all().delete()
    apps.get_model('net', 'ComputerAnalysis').objects.using(alias).all().delete()
    apps.get_model('net', 'ComputerLogFile').objects.using(alias).all().delete()

    Task = apps.get_model('net', 'TaskRun')
    Target = apps.get_model('net', 'TaskTargetRun')
    task_ids = list(Task.objects.using(alias).filter(
        task_type__in=('computer_fetch', 'computer_analysis')).values_list('pk', flat=True))
    if task_ids:
        target_ids = list(Target.objects.using(alias).filter(
            task_id__in=task_ids).values_list('pk', flat=True))
        apps.get_model('net', 'AlertEvent').objects.using(alias).filter(
            Q(task_id__in=task_ids) | Q(summary_task_id__in=task_ids) |
            Q(target_run_id__in=target_ids)
        ).delete()
        apps.get_model('net', 'DeviceConfigurationBackup').objects.using(alias).filter(
            task_target_id__in=target_ids).update(task_target_id=None)
        for model_name in ('ComputerAnalysis', 'Network_Device_Inspection',
                           'Server_Inspection', 'Monitor_Inspection'):
            apps.get_model('net', model_name).objects.using(alias).filter(
                task_target_id__in=target_ids).update(task_target_id=None)
        Target.objects.using(alias).filter(pk__in=target_ids).delete()
        Task.objects.using(alias).filter(pk__in=task_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0054_pc_analysis_log_reference'),
    ]

    operations = [
        migrations.RunPython(delete_retired_pc_source_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='computerlogarchive',
            name='log_file',
        ),
        migrations.RemoveIndex(
            model_name='computerlogtransfer',
            name='net_pc_xfer_source_stage_idx',
        ),
        migrations.RemoveConstraint(
            model_name='computerlogtransfer',
            name='net_pc_transfer_active_identity_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='pclogsourceconfig',
            name='net_pc_log_source_singleton_ck',
        ),
        migrations.RemoveConstraint(
            model_name='pclogsourceconfig',
            name='net_pc_log_source_type_ck',
        ),
        migrations.RemoveField(
            model_name='pclogsourcecredential',
            name='source',
        ),
        migrations.RemoveConstraint(
            model_name='computerlogfile',
            name='net_pc_import_identity_ck',
        ),
        migrations.RemoveConstraint(
            model_name='taskrun',
            name='net_task_binding_shape_ck',
        ),
        migrations.RemoveField(
            model_name='tasktargetrun',
            name='analysis_handoff_task',
        ),
        migrations.RemoveField(
            model_name='tasktargetrun',
            name='fetched_logs',
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('domain_sync', '域控同步'), ('inspection', '设备巡检'), ('computer_analysis', '计算机日志分析'), ('people_test', '人员目录连接测试'), ('people_preview', '人员目录同步预览'), ('people_sync', '人员自动同步'), ('domain_operation', '域控操作'), ('access_sync', '门禁记录采集')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktargetrun',
            name='target_type',
            field=models.CharField(choices=[('domain_config', '域控目录'), ('network_device', '网络设备'), ('server', '服务器'), ('monitor', '安防设备'), ('computer_log', '计算机日志'), ('people_source', '人员目录来源'), ('domain_account', '域账号'), ('domain_computer', '域计算机'), ('access_source', '门禁平台来源')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_source__isnull', False), ('schedule__isnull', True), ('source', 'manual'), ('task_type__in', ('people_test', 'people_preview'))), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', False), ('schedule__isnull', False), ('source', 'scheduled'), ('task_type', 'people_sync')), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', False), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'inspection')), models.Q(('analysis_profile__isnull', False), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'computer_analysis')), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('task_type', 'domain_sync')), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('schedule__isnull', True), ('source', 'manual'), ('task_type', 'domain_operation')), models.Q(('analysis_profile__isnull', True), ('inspection_profile__isnull', True), ('people_applied_at__isnull', True), ('people_source__isnull', True), ('schedule__isnull', True), ('source', 'manual'), ('task_type', 'access_sync')), _connector='OR'), name='net_task_binding_shape_ck'),
        ),
        migrations.DeleteModel(
            name='ComputerLogArchive',
        ),
        migrations.RemoveField(
            model_name='computerlogtransfer',
            name='log_file',
        ),
        migrations.RemoveField(
            model_name='computerlogtransfer',
            name='source',
        ),
        migrations.RemoveField(
            model_name='computerlogtransfer',
            name='task_target',
        ),
        migrations.DeleteModel(
            name='PCLogSourceCredential',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='archived_path',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='import_status',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='legacy_payload',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='parse_error',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='remote_source_path',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='source_path',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='source_protocol',
        ),
        migrations.DeleteModel(
            name='PCLogSourceConfig',
        ),
        migrations.DeleteModel(
            name='ComputerLogTransfer',
        ),
        migrations.AlterField(
            model_name='computerlogfile',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='log_files', to='net.computer'),
        ),
        migrations.AlterField(
            model_name='computerlogfile',
            name='collected_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='computerlogfile',
            name='collected_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='computerlogfile',
            name='platform',
            field=models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS')], max_length=20),
        ),
    ]
