# Generated by Django 6.1.1 on 2026-09-19 06:12

from django.db import migrations, models


def backfill_actionable_issue_counts(apps, schema_editor):
    ComputerAnalysis = apps.get_model('net', 'ComputerAnalysis')
    for analysis in ComputerAnalysis.objects.only('pk', 'status', 'exceptions').iterator(chunk_size=500):
        count = sum(
            1 for issue in analysis.exceptions or []
            if isinstance(issue, dict) and issue.get('severity') != 'info'
        )
        ComputerAnalysis.objects.filter(pk=analysis.pk).update(actionable_issue_count=count)


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0055_remove_pc_shared_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerlogfile',
            name='identity_match',
        ),
        migrations.RemoveField(
            model_name='computerlogfile',
            name='log_metadata',
        ),
        migrations.AddField(
            model_name='computeranalysis',
            name='actionable_issue_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_actionable_issue_counts, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Error_Computer',
        ),
    ]
