# Generated by Django 6.1.1 on 2026-09-19 12:47

import django.core.validators
import django.db.models.deletion
import net.models.topology
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0057_repair_pc_log_projections'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTopologyInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.CharField(max_length=255)),
                ('if_index', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('mac_address', models.CharField(blank=True, max_length=64)),
                ('admin_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('testing', 'Testing'), ('unknown', 'Unknown'), ('dormant', 'Dormant'), ('not_present', 'Not present'), ('lower_layer_down', 'Lower layer down')], default='unknown', max_length=24)),
                ('oper_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('testing', 'Testing'), ('unknown', 'Unknown'), ('dormant', 'Dormant'), ('not_present', 'Not present'), ('lower_layer_down', 'Lower layer down')], default='unknown', max_length=24)),
                ('speed_bps', models.PositiveBigIntegerField(blank=True, null=True)),
                ('vlan_ids', models.JSONField(blank=True, default=list, validators=[net.models.topology.validate_vlan_list])),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_stale', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topology_interfaces', to='net.network_device')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTopologyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_link_key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', '链路键必须是 SHA-256。')])),
                ('remote_chassis_id', models.CharField(blank=True, max_length=255)),
                ('remote_port_id', models.CharField(blank=True, max_length=255)),
                ('remote_port_description', models.CharField(blank=True, max_length=1000)),
                ('remote_system_name', models.CharField(blank=True, max_length=255)),
                ('remote_management_addresses', models.JSONField(blank=True, default=list, validators=[net.models.topology.validate_string_list])),
                ('protocols', models.JSONField(blank=True, default=list, validators=[net.models.topology.validate_string_list])),
                ('evidence_direction', models.CharField(choices=[('unilateral', '单侧'), ('bidirectional', '双向')], default='unilateral', max_length=16)),
                ('resolution_status', models.CharField(choices=[('resolved', '已解析'), ('unresolved', '未解析'), ('conflict', '冲突')], default='unresolved', max_length=16)),
                ('status', models.CharField(choices=[('current', '当前'), ('stale', '陈旧')], default='current', max_length=16)),
                ('speed_bps', models.PositiveBigIntegerField(blank=True, null=True)),
                ('vlan_ids', models.JSONField(blank=True, default=list, validators=[net.models.topology.validate_vlan_list])),
                ('confidence', models.DecimalField(decimal_places=2, default='0.60', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('missing_complete_batches', models.PositiveIntegerField(default=0)),
                ('local_interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_links', to='net.networktopologyinterface')),
                ('remote_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_topology_links', to='net.network_device')),
                ('remote_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_links', to='net.networktopologyinterface')),
            ],
        ),
        migrations.CreateModel(
            name='TopologyDiscoveryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('snmp_lldp', 'SNMP LLDP'), ('ssh_lldp', 'SSH LLDP'), ('ssh_cdp', 'SSH CDP'), ('mixed', '混合证据')], max_length=16)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('cancelled', '已取消')], default='running', max_length=16)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('interface_count', models.PositiveIntegerField(default=0)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('unresolved_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topology_batches', to='net.network_device')),
                ('source_target', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='topology_batch', to='net.tasktargetrun')),
                ('source_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topology_batches', to='net.taskrun')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTopologyObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('snmp_lldp', 'SNMP LLDP'), ('ssh_lldp', 'SSH LLDP'), ('ssh_cdp', 'SSH CDP'), ('mixed', '混合证据')], max_length=16)),
                ('neighbor', models.JSONField(blank=True, default=dict, validators=[net.models.topology.validate_json_object])),
                ('evidence', models.TextField(max_length=65536)),
                ('evidence_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', '证据摘要必须是 SHA-256。')])),
                ('collected_at', models.DateTimeField()),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='net.networktopologylink')),
                ('local_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topology_observations', to='net.network_device')),
                ('local_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='net.networktopologyinterface')),
                ('source_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topology_observations', to='net.tasktargetrun')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='net.topologydiscoverybatch')),
            ],
            options={
                'permissions': [('view_topology_evidence', 'Can view topology evidence')],
            },
        ),
        migrations.AddField(
            model_name='networktopologylink',
            name='last_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='net.topologydiscoverybatch'),
        ),
        migrations.AddField(
            model_name='networktopologyinterface',
            name='last_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='net.topologydiscoverybatch'),
        ),
        migrations.AddIndex(
            model_name='topologydiscoverybatch',
            index=models.Index(fields=['device', '-collected_at'], name='net_topobatch_device_time_idx'),
        ),
        migrations.AddIndex(
            model_name='topologydiscoverybatch',
            index=models.Index(fields=['status', '-started_at'], name='net_topobatch_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='topologydiscoverybatch',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='net_topobatch_schema_positive_ck'),
        ),
        migrations.AddIndex(
            model_name='networktopologyobservation',
            index=models.Index(fields=['batch', 'collected_at'], name='net_topoobs_batch_time_idx'),
        ),
        migrations.AddIndex(
            model_name='networktopologyobservation',
            index=models.Index(fields=['collected_at'], name='net_topoobs_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='networktopologyobservation',
            constraint=models.UniqueConstraint(fields=('batch', 'evidence_sha256'), name='net_topoobs_batch_digest_uniq'),
        ),
        migrations.AddIndex(
            model_name='networktopologylink',
            index=models.Index(fields=['status', 'last_seen_at'], name='net_topolink_status_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='networktopologylink',
            index=models.Index(fields=['remote_device', 'status'], name='net_topolink_remote_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='networktopologylink',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='net_topolink_confidence_range_ck'),
        ),
        migrations.AddIndex(
            model_name='networktopologyinterface',
            index=models.Index(fields=['device', 'last_seen_at'], name='net_topointf_device_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='networktopologyinterface',
            index=models.Index(fields=['mac_address'], name='net_topointf_mac_idx'),
        ),
        migrations.AddConstraint(
            model_name='networktopologyinterface',
            constraint=models.UniqueConstraint(fields=('device', 'stable_key'), name='net_topointf_device_key_uniq'),
        ),
    ]
