# Generated by Django 6.1.1 on 2026-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0059_rename_securitydevice_weakcurrentdevice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='computeranalysis',
            index=models.Index(fields=['-created_at'], name='net_pcanalysis_created_idx'),
        ),
        migrations.AddIndex(
            model_name='monitor_inspection',
            index=models.Index(fields=['-created_at'], name='net_monitorinsp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='network_device_inspection',
            index=models.Index(fields=['-created_at'], name='net_netdevinsp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='server_inspection',
            index=models.Index(fields=['-created_at'], name='net_serverinsp_created_idx'),
        ),
    ]
