# Generated by Django 6.1.1 on 2026-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0060_record_created_at_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='net_schedule_kind_fields_ck',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='interval_unit',
            field=models.CharField(blank=True, choices=[('seconds', '秒'), ('minutes', '分钟'), ('hours', '小时')], default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('daily_time__isnull', True), ('interval_unit__in', ('seconds', 'minutes', 'hours')), ('interval_value__gt', 0), ('interval_value__isnull', False), ('kind', 'interval')), models.Q(('daily_time__isnull', False), ('interval_unit', ''), ('interval_value__isnull', True), ('kind', 'daily')), _connector='OR'), name='net_schedule_kind_fields_ck'),
        ),
    ]
