# Generated by Django 6.1.1 on 2026-10-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0061_schedule_seconds_interval_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionprofile',
            name='record_retention',
            field=models.CharField(choices=[('none', '不保留历史（仅保留每台设备最新一条）'), ('30', '保留 30 天'), ('90', '保留 90 天'), ('180', '保留 180 天')], default='180', max_length=8),
        ),
    ]
