# Generated by Django 6.1.1 on 2026-10-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0062_inspection_record_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistoryConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('retention_days', models.CharField(choices=[('30', '保留 30 天'), ('90', '保留 90 天'), ('180', '保留 180 天')], default='90', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='net_task_history_singleton_ck')],
            },
        ),
    ]
