# Generated by Django 6.1.1 on 2026-10-05 14:21

import net.infrastructure.credentials
import net.models.alerts
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0063_task_history_retention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='settings',
            field=net.infrastructure.credentials.EncryptedJSONField(default=dict, validators=[net.models.alerts.validate_finite_json]),
        ),
        migrations.AlterField(
            model_name='domain_controller_config',
            name='bind_password',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='network_device',
            name='api_shared_secret',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='network_device',
            name='password',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='network_device',
            name='snmp_auth_password',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='network_device',
            name='snmp_community',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='network_device',
            name='snmp_priv_password',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='peoplesyncsource',
            name='credentials',
            field=net.infrastructure.credentials.EncryptedJSONField(default=dict, editable=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='api_token',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='weakcurrentdevice',
            name='api_password',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='weakcurrentdevice',
            name='api_token',
            field=net.infrastructure.credentials.EncryptedCharField(blank=True, max_length=1024, null=True),
        ),
    ]
