"""
Django settings for net project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from net.infrastructure.environment import load_environment

load_environment()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Stable service encryption keys; the Web and Worker must share each value.
DOMAIN_OPERATION_ENCRYPTION_KEY = os.getenv('DOMAIN_OPERATION_ENCRYPTION_KEY', '')
PC_LOG_SOURCE_ENCRYPTION_KEY = os.getenv('PC_LOG_SOURCE_ENCRYPTION_KEY', '')
DEVICE_BACKUP_ENCRYPTION_KEY = os.getenv('DEVICE_BACKUP_ENCRYPTION_KEY', '')
# Forwarded host and scheme are trusted only when the deployment explicitly
# enables this setting for a proxy that it controls.
NET_TRUST_PROXY_HEADERS = (
    os.getenv('NET_TRUST_PROXY_HEADERS', 'false').strip().lower()
    in {'1', 'true', 'yes'}
)
SECURE_PROXY_SSL_HEADER = None
USE_X_FORWARDED_HOST = False
if NET_TRUST_PROXY_HEADERS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-change-me',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaulting to 'false' makes an unconfigured deployment fail loudly at the secret-key
# gate below instead of silently serving tracebacks. A developer who wants tracebacks
# opts in with DJANGO_DEBUG=true.
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() in {'1', 'true', 'yes'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]

# Startup gate. deploy/setup.py checks the same rules while installing, but that runs
# once; without this a .env that is missing, moved or typo'd starts the service silently
# with DEBUG and a publicly known SECRET_KEY, which leaks tracebacks and lets anyone
# forge session cookies and password-reset tokens.
_INSECURE_SECRET_KEYS = frozenset({
    'django-insecure-local-development-only-change-me',
    'changeme',
    'change-me',
    'replace-with-random-secret',
})
if not DEBUG:
    if SECRET_KEY in _INSECURE_SECRET_KEYS or len(SECRET_KEY) < 32:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be an explicit 32+ character secret when DJANGO_DEBUG is off. '
            'A known key lets anyone forge sessions and password-reset tokens. '
            'Restore the key from your .env, or re-run deploy/setup.py to generate one.'
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'net',
    'index',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'index.common.access.AccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'net.infrastructure.page_cache.PageCacheMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'net.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'index.common.access.access_context',
            ],
        },
    },
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

WSGI_APPLICATION = 'net.wsgi.application'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Imported for its connection_created receiver, not for sqlite_timeout below.
import net.infrastructure.database  # noqa: F401

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').strip().lower()

if DB_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'net'),
            'USER': os.getenv('DB_USER', 'admin'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {'charset': 'utf8mb4', 'isolation_level': 'read committed',
                        'init_command': "SET sql_mode='STRICT_TRANS_TABLES', time_zone='+00:00'", 'connect_timeout': 5},
            # 保持 Django 默认的 test_<库名>：单元测试每次重建、用完即弃，不能碰 net 或 net-test。
            # net-test 是 demo 的常驻库（deploy.demo 用它），里面可能存着真实迁移数据。
            'TEST': {'NAME': os.getenv('DB_TEST_NAME', 'test_' + os.getenv('DB_NAME', 'net'))},
        }
    }
elif DB_ENGINE == 'sqlite':
    from net.infrastructure.database import sqlite_timeout

    sqlite_database_path = os.getenv('DJANGO_SQLITE_PATH', '').strip()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_database_path or BASE_DIR / 'db.sqlite3',
            'OPTIONS': {'timeout': sqlite_timeout(os.getenv('NET_SQLITE_TIMEOUT', '5'))},
        }
    }
elif DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'net'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
            # MySQL 那边的 sql_mode/time_zone 在这里是连接参数：PostgreSQL 的会话
            # 时区决定 timestamp 怎么落盘，必须和 USE_TZ 一样锁在 UTC。
            'OPTIONS': {'options': '-c timezone=UTC -c statement_timeout=30000'},
            'TEST': {'NAME': os.getenv('DB_TEST_NAME', 'test_' + os.getenv('DB_NAME', 'net'))},
        }
    }
else:
    # Refuse to fall through to SQLite: a mistyped engine would otherwise open a
    # different, empty database and read as if every record had vanished.
    raise ImproperlyConfigured(
        f'DB_ENGINE must be "mysql", "sqlite" or "postgresql"; got {DB_ENGINE!r}.')


# Permission for the explicit sqlite_wal maintenance command, not a startup hook.
NET_PAGE_CACHE_ENABLED = os.getenv('NET_PAGE_CACHE_ENABLED', 'false').lower() in {'1', 'true', 'yes'}
NET_PAGE_CACHE_SECONDS = int(os.getenv('NET_PAGE_CACHE_SECONDS', '15'))
CACHES = {
    'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'},
    'pages': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('NET_REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'KEY_PREFIX': 'net-inspection',
        'TIMEOUT': NET_PAGE_CACHE_SECONDS,
        'OPTIONS': {'socket_connect_timeout': 0.2, 'socket_timeout': 0.2},
    },
}

NET_SQLITE_WAL_ENABLED = os.getenv('NET_SQLITE_WAL_ENABLED', 'false').strip().lower() in {'1', 'true', 'yes'}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.getenv('DJANGO_STATIC_ROOT', str(BASE_DIR / 'staticfiles')))

# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = int(os.getenv('NET_SESSION_COOKIE_AGE', '36000'))


def _net_flag(name, default='false'):
    return os.getenv(name, default).strip().lower() in {'1', 'true', 'yes'}


# HTTPS hardening. All of it stays off unless the deployment turns it on, because a
# site reached over plain HTTP would redirect itself to an address it cannot serve,
# and browsers drop (not downgrade) Secure cookies, which locks everyone out.
# Turn NET_SECURE_SSL_REDIRECT on only together with NET_SECURE_COOKIES and a proxy
# that sets X-Forwarded-Proto; NET_SECURE_HSTS_SECONDS is deliberately 0 until the
# HTTPS path has proven stable, since HSTS cannot be withdrawn from a client.
NET_SECURE_COOKIES = _net_flag('NET_SECURE_COOKIES')
SESSION_COOKIE_SECURE = NET_SECURE_COOKIES
CSRF_COOKIE_SECURE = NET_SECURE_COOKIES
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_SSL_REDIRECT = _net_flag('NET_SECURE_SSL_REDIRECT')
SECURE_REFERRER_POLICY = os.getenv('NET_SECURE_REFERRER_POLICY', 'same-origin')
SECURE_HSTS_SECONDS = int(os.getenv('NET_SECURE_HSTS_SECONDS', '0'))
if SECURE_HSTS_SECONDS:
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False


# Login throttling. django-axes is not a dependency and the counters only need to
# outlive a burst, so the cache is enough; a cache outage must not lock anyone out,
# hence the try/except in the middleware.
NET_LOGIN_MAX_FAILURES = int(os.getenv('NET_LOGIN_MAX_FAILURES', '5'))
# The per-source limit is deliberately looser than the per-account one: a whole office
# usually shares one NAT address, so an equal limit would let a handful of typos lock
# everyone out. The account counter is what actually stops one account being guessed.
NET_LOGIN_IP_MAX_FAILURES = int(os.getenv('NET_LOGIN_IP_MAX_FAILURES', '20'))
NET_LOGIN_WINDOW_SECONDS = int(os.getenv('NET_LOGIN_WINDOW_SECONDS', '900'))
NET_LOGIN_LOCK_SECONDS = int(os.getenv('NET_LOGIN_LOCK_SECONDS', '900'))


# Logging. Without this the project-wide logger calls fall through to Python's
# lastResort handler (stderr, WARNING+, no format), so level and destination could
# not be configured per environment. deploy/service.py already captures the Worker
# streams, so console is the right default for both roles.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '{asctime} {levelname} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'net': {
            'handlers': ['console'],
            'level': os.getenv('NET_LOG_LEVEL', 'INFO' if not DEBUG else 'DEBUG'),
            'propagate': False,
        },
        'index': {
            'handlers': ['console'],
            'level': os.getenv('NET_LOG_LEVEL', 'INFO' if not DEBUG else 'DEBUG'),
            'propagate': False,
        },
    },
}