"""
Django settings for net project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from net.infrastructure.environment import load_environment

load_environment()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Stable service encryption keys; the Web and Worker must share each value.
DOMAIN_OPERATION_ENCRYPTION_KEY = os.getenv('DOMAIN_OPERATION_ENCRYPTION_KEY', '')
PC_LOG_SOURCE_ENCRYPTION_KEY = os.getenv('PC_LOG_SOURCE_ENCRYPTION_KEY', '')
DEVICE_BACKUP_ENCRYPTION_KEY = os.getenv('DEVICE_BACKUP_ENCRYPTION_KEY', '')
# Forwarded host and scheme are trusted only when the deployment explicitly
# enables this setting for a proxy that it controls.
NET_TRUST_PROXY_HEADERS = (
    os.getenv('NET_TRUST_PROXY_HEADERS', 'false').strip().lower()
    in {'1', 'true', 'yes'}
)
SECURE_PROXY_SSL_HEADER = None
USE_X_FORWARDED_HOST = False
if NET_TRUST_PROXY_HEADERS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-change-me',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() in {'1', 'true', 'yes'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'net',
    'index',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'index.common.access.AccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'net.infrastructure.page_cache.PageCacheMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'net.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'index.common.access.access_context',
            ],
        },
    },
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

WSGI_APPLICATION = 'net.wsgi.application'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if os.getenv('DB_ENGINE', 'sqlite').lower() == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'net'),
            'USER': os.getenv('DB_USER', 'admin'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {'charset': 'utf8mb4', 'isolation_level': 'read committed',
                        'init_command': "SET sql_mode='STRICT_TRANS_TABLES', time_zone='+00:00'", 'connect_timeout': 5},
        }
    }
else:
    from net.infrastructure.database import sqlite_timeout

    sqlite_database_path = os.getenv('DJANGO_SQLITE_PATH', '').strip()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_database_path or BASE_DIR / 'db.sqlite3',
            'OPTIONS': {'timeout': sqlite_timeout(os.getenv('NET_SQLITE_TIMEOUT', '5'))},
        }
    }

# Permission for the explicit sqlite_wal maintenance command, not a startup hook.
NET_PAGE_CACHE_ENABLED = os.getenv('NET_PAGE_CACHE_ENABLED', 'false').lower() in {'1', 'true', 'yes'}
NET_PAGE_CACHE_SECONDS = int(os.getenv('NET_PAGE_CACHE_SECONDS', '15'))
CACHES = {
    'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'},
    'pages': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('NET_REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'KEY_PREFIX': 'net-inspection',
        'TIMEOUT': NET_PAGE_CACHE_SECONDS,
        'OPTIONS': {'socket_connect_timeout': 0.2, 'socket_timeout': 0.2},
    },
}

NET_SQLITE_WAL_ENABLED = os.getenv('NET_SQLITE_WAL_ENABLED', 'false').strip().lower() in {'1', 'true', 'yes'}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.getenv('DJANGO_STATIC_ROOT', str(BASE_DIR / 'staticfiles')))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = 36000